name: Bikeshare Model CI/CD

on:
  push:
    branches: [ main ]

jobs:
  train-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest build
          if [ -f bikeshare_project/requirements.txt ]; then pip install -r bikeshare_project/requirements.txt; fi
      
      - name: Train model
        run: |
          cd bikeshare_project
          python train_pipeline.py
      
      - name: Run prediction
        run: |
          cd bikeshare_project
          python predict.py
      
      - name: Run tests
        run: |
          cd bikeshare_project
          pytest
      
      - name: Build package
        run: |
          cd bikeshare_project
          python -m build
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: bikeshare_project/dist/*.whl
  
  build-and-push-docker:
    needs: train-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: bikeshare_model_api
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./bikeshare_model_api
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bikeshare-api:latest
